#!/bin/bash
#
#   A tool to standardize the working backup naming style.
#
#   FCDAS - Kyle Eberhart - 22APR14
#         - Kyle Eberhart - 14MAY20 - Put files in a backup folder and add
#         versioning so we can safely delete the oldes backups. Part of a set
#         adding a tool called unbu to restore the newest backup.
#         - Kyle Eberhart - 14AUG20 - Put a limit on the number of backups to
#         make for each file. Less than 10
#
#-----------------------------------------------------------------------------

bu_limit="10"
bu_dir="$HOME/backups/working_backups"

files=( $@ )
if [ $# -eq 0 ]; then
    echo ""
    echo "  Create pre modification backup of a file appending date and time"
    echo "  of backup creation."
    echo ""
    echo "      usage: bu filename"
    echo ""
    exit
fi

for file in "${files[@]}"; do
    # read our filename and path
    source_full_path=$(realpath $file)
    path_without_file=${source_full_path%/*}
    # create the correct bu directory if it isn't there
    [ ! -d "$bu_dir" ] && mkdir -p "$bu_dir"
    work_dir=$bu_dir$path_without_file
    [ ! -d "$work_dir" ] && mkdir -p "$work_dir"
    # figure out our filename and make the new name
    file_name=${source_full_path##*/}
    new_name="${file_name}.1"
    # where are we putting the file
    storage_full_path="${work_dir}/${new_name}"
    # copy the file if we can, else increment and then copy
    if [[ ! -f $storage_full_path ]]; then
        cp -p -v $source_full_path $storage_full_path
    else
        # what are we looking for
        search_full_path="${work_dir}/${file_name}"
        # list the files already there
        old_file_list=$(ls -d $search_full_path* | sort -n -r)
        for old_file in ${old_file_list}; do
            # increment the file number
            dot_number=${old_file##$search_full_path}
            number=${dot_number##.}
            number=$(($number + 1))
            if [ "$number" -lt "$bu_limit" ]; then
                new_number_name="${search_full_path}.${number}"
                cp -p $old_file $new_number_name
            fi
        done
        # finally we copy the newest backup
        cp -p -v $source_full_path $storage_full_path
    fi
done

#date=$(/bin/date +%d%b%y-%H%M%S)
#for file in "${files[@]}"; do
#    if [[ $file == *.* ]]; then
#        new_name=${file/'.'/"_bak_$date."}
#    else
#        new_name="${file}_bak_${date}"
#    fi
#    cp -p -v $file $new_name
#done
